### ISSUE TITLE
Does not compile with libpng 1.5

### ISSUE THREAD

**Issue by moepman** [blinry/gish#2]
Gish does not compile with libpng 1.5 (on linux) because the full definition of png_info_def is no longer visible to the application.

[ 98%] Building C object CMakeFiles/gish.dir/video/texture.c.o  
/home/markus/workspace/gish/video/texture.c: In function ‘loadtexturepng’:  
/home/markus/workspace/gish/video/texture.c:98:14: error: dereferencing pointer to incomplete type
/home/markus/workspace/gish/video/texture.c:102:14: error: dereferencing pointer to incomplete type
/home/markus/workspace/gish/video/texture.c:102:61: error: dereferencing pointer to incomplete type
/home/markus/workspace/gish/video/texture.c:106:14: error: dereferencing pointer to incomplete type
/home/markus/workspace/gish/video/texture.c:110:14: error: dereferencing pointer to incomplete type
/home/markus/workspace/gish/video/texture.c:114:14: error: dereferencing pointer to incomplete type
/home/markus/workspace/gish/video/texture.c:114:42: error: dereferencing pointer to incomplete type
/home/markus/workspace/gish/video/texture.c:118:14: error: dereferencing pointer to incomplete type
/home/markus/workspace/gish/video/texture.c:127:21: error: dereferencing pointer to incomplete type
/home/markus/workspace/gish/video/texture.c:128:21: error: dereferencing pointer to incomplete type
make[2]: **\* [CMakeFiles/gish.dir/video/texture.c.o] Error 1
